version: "3.9"
services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    ports: 
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: "Todo"
    restart: unless-stopped

  # do not run this service if app is to be run locally
  todo-api:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-api
    depends_on:
      - "mysql"
    ports:
      - "4000:3000"
    restart: always
